# Generated by Django 4.2.4 on 2023-08-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0003_alter_author_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='followers',
        ),
    ]
