# Generated by Django 4.2.4 on 2023-08-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0004_remove_author_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='eshopping.author'),
        ),
    ]
