# Generated by Django 4.2.4 on 2023-08-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0006_author_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshopping.publisher'),
        ),
    ]
